Parameters:
  ImagesDomain:
    Type: String
  ApiSecret:
    Type: String

Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: code
        S3Key: index.zip
      FunctionName: invalidate-cdn
      Handler: index.handler
      Runtime: nodejs8.10
      Role: arn:aws:iam::123456:role/role-name
      Environment:
        Variables:
          IMAGES_DOMAIN: !Ref ImagesDomain
          API_SECRET: !Ref ApiSecret
