Parameters:
  ImagesDomain:
    Type: String
    Default: https://pixboost.com
  ApiSecret:
    Type: String
  ImageUrlPrefix:
    Type: String
  LambdaRole:
    Type: String

Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: __CODE__
      FunctionName: invalidate-cdn
      Handler: index.handler
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      Environment:
        Variables:
          IMAGES_DOMAIN: !Ref ImagesDomain
          API_SECRET: !Ref ApiSecret
          IMAGE_URL_PREFIX: !Ref ImageUrlPrefix
